-- =====================================================
-- SKU COST AUTHORITATIVE IMPORT
-- Generated: 2026-02-05T02:04:44.702Z
-- Source: omen_cost_ledger_v1.csv
-- Valid costs: 296
-- Invalid/missing: 11
-- =====================================================

-- Clear existing data (authoritative replace)
TRUNCATE TABLE public.sku_costs;

-- Insert all valid SKU costs
INSERT INTO public.sku_costs (sku, unit_cost, effective_date, source) VALUES
  ('BLOOPIEZ-3.5G', 7.00, NOW(), 'excel_authoritative_import'),
  ('BLOOPIEZ-7G', 13.00, NOW(), 'excel_authoritative_import'),
  ('BLOOPIEZ-14G', 25.00, NOW(), 'excel_authoritative_import'),
  ('BLOOPIEZ-28G', 50.00, NOW(), 'excel_authoritative_import'),
  ('ZOAP-3.5', 7.00, NOW(), 'excel_authoritative_import'),
  ('ZOAP-7G', 13.00, NOW(), 'excel_authoritative_import'),
  ('ZOAP-14G', 25.00, NOW(), 'excel_authoritative_import'),
  ('ZOAP-28G', 50.00, NOW(), 'excel_authoritative_import'),
  ('DOSI POP-3.5G', 7.00, NOW(), 'excel_authoritative_import'),
  ('DOSI POP-7G', 13.00, NOW(), 'excel_authoritative_import'),
  ('DOSI POP-14G', 25.00, NOW(), 'excel_authoritative_import'),
  ('DOSI POP-28G', 50.00, NOW(), 'excel_authoritative_import'),
  ('MAI TAI-3.5G', 7.00, NOW(), 'excel_authoritative_import'),
  ('MAI TAI-7G', 13.00, NOW(), 'excel_authoritative_import'),
  ('MAI TAI-14G', 25.00, NOW(), 'excel_authoritative_import'),
  ('MAI TAI-28G', 50.00, NOW(), 'excel_authoritative_import'),
  ('BLUE MINTS-3.5G', 7.00, NOW(), 'excel_authoritative_import'),
  ('BLUE MINTS-7G', 13.00, NOW(), 'excel_authoritative_import'),
  ('BLUE MINTS-14G', 25.00, NOW(), 'excel_authoritative_import'),
  ('BLUE MINTS-28G', 50.00, NOW(), 'excel_authoritative_import'),
  ('TOP-TROP CHERRY-3.5G', 9.00, NOW(), 'excel_authoritative_import'),
  ('TOP-TROP CHERRY-7G', 17.00, NOW(), 'excel_authoritative_import'),
  ('TOP-TROP CHERRY-14G', 33.00, NOW(), 'excel_authoritative_import'),
  ('TOP-TROP CHERRY-28G', 65.00, NOW(), 'excel_authoritative_import'),
  ('MEGA-Z-3.5G', 9.00, NOW(), 'excel_authoritative_import'),
  ('MEGA-Z-7G', 17.00, NOW(), 'excel_authoritative_import'),
  ('MEGA-Z-14G', 33.00, NOW(), 'excel_authoritative_import'),
  ('MEGA-Z-28G', 65.00, NOW(), 'excel_authoritative_import'),
  ('WAGYU-3.5G', 9.00, NOW(), 'excel_authoritative_import'),
  ('WAGYU-7G', 17.00, NOW(), 'excel_authoritative_import'),
  ('WAGYU-14G', 33.00, NOW(), 'excel_authoritative_import'),
  ('WAGYU-28G', 65.00, NOW(), 'excel_authoritative_import'),
  ('ZZ4-3.5G', 9.00, NOW(), 'excel_authoritative_import'),
  ('ZZ4-7G', 17.00, NOW(), 'excel_authoritative_import'),
  ('ZZ4-14G', 33.00, NOW(), 'excel_authoritative_import'),
  ('ZZ4-28G', 65.00, NOW(), 'excel_authoritative_import'),
  ('BUDDHA''S HAND-3.5G', 10.00, NOW(), 'excel_authoritative_import'),
  ('BUDDHA''S HAND-7G', 19.00, NOW(), 'excel_authoritative_import'),
  ('BUDDHA''S HAND-14G', 38.00, NOW(), 'excel_authoritative_import'),
  ('BUDDHA''S HAND-28G', 75.00, NOW(), 'excel_authoritative_import'),
  ('BUBBLEGUM BREATH-3.5G', 10.00, NOW(), 'excel_authoritative_import'),
  ('BUBBLEGUM BREATH-7G', 19.00, NOW(), 'excel_authoritative_import'),
  ('BUBBLEGUM BREATH-14G', 38.00, NOW(), 'excel_authoritative_import'),
  ('BUBBLEGUM BREATH-28G', 75.00, NOW(), 'excel_authoritative_import'),
  ('BLACK RUSSIAN-3.5G', 10.00, NOW(), 'excel_authoritative_import'),
  ('BLACK RUSSIAN-7G', 19.00, NOW(), 'excel_authoritative_import'),
  ('BLACK RUSSIAN-14G', 38.00, NOW(), 'excel_authoritative_import'),
  ('BLACK RUSSIAN-28G', 75.00, NOW(), 'excel_authoritative_import'),
  ('AFTERNOON DELIGHT-3.5G', 12.00, NOW(), 'excel_authoritative_import'),
  ('AFTERNOON DELIGHT-14G', 45.00, NOW(), 'excel_authoritative_import'),
  ('PEACH RINGZ-3.5G', 12.00, NOW(), 'excel_authoritative_import'),
  ('PEACH RINGZ-14G', 45.00, NOW(), 'excel_authoritative_import'),
  ('WHITE CHOCOLATE-3.5G', 12.00, NOW(), 'excel_authoritative_import'),
  ('WHITE CHOCOLATE-14G', 45.00, NOW(), 'excel_authoritative_import'),
  ('BLUE NERDZ-3.5G', 12.00, NOW(), 'excel_authoritative_import'),
  ('BLUE NERDZ-14G', 45.00, NOW(), 'excel_authoritative_import'),
  ('LIP SMACKERZ-3.5G', 12.00, NOW(), 'excel_authoritative_import'),
  ('LIP SMACKERZ-14G', 45.00, NOW(), 'excel_authoritative_import'),
  ('JOKERS-3.5G', 12.00, NOW(), 'excel_authoritative_import'),
  ('JOKERS-14G', 45.00, NOW(), 'excel_authoritative_import'),
  ('VENOM-CART-01', 8.00, NOW(), 'excel_authoritative_import'),
  ('VENOM-CART-02', 8.00, NOW(), 'excel_authoritative_import'),
  ('VENOM-CART-03', 8.00, NOW(), 'excel_authoritative_import'),
  ('VENOM-CART-04', 8.00, NOW(), 'excel_authoritative_import'),
  ('VENOM-CART-05', 8.00, NOW(), 'excel_authoritative_import'),
  ('SAUCE-BARS-1G-01', 25.00, NOW(), 'excel_authoritative_import'),
  ('SAUCE-BARS-1G-02', 25.00, NOW(), 'excel_authoritative_import'),
  ('SAUCE-BARS-1G-03', 25.00, NOW(), 'excel_authoritative_import'),
  ('SAUCE-BARS-1G-04', 25.00, NOW(), 'excel_authoritative_import'),
  ('SAUCE-BARS-1G-05', 25.00, NOW(), 'excel_authoritative_import'),
  ('SAUCE-BARS-1G-06', 25.00, NOW(), 'excel_authoritative_import'),
  ('SAUCE-BARS-1G-07', 25.00, NOW(), 'excel_authoritative_import'),
  ('SAUCE-BARS-1G-08', 25.00, NOW(), 'excel_authoritative_import'),
  ('TORCH-FLOW-1G-01', 28.00, NOW(), 'excel_authoritative_import'),
  ('TORCH-FLOW-1G-02', 28.00, NOW(), 'excel_authoritative_import'),
  ('TORCH-FLOW-1G-03', 28.00, NOW(), 'excel_authoritative_import'),
  ('TORCH-FLOW-1G-04', 28.00, NOW(), 'excel_authoritative_import'),
  ('MUHA-MEDAS-2G-01', 16.00, NOW(), 'excel_authoritative_import'),
  ('MUHA-MEDAS-2G-02', 16.00, NOW(), 'excel_authoritative_import'),
  ('MUHA-MEDAS-2G-03', 16.00, NOW(), 'excel_authoritative_import'),
  ('MUHA-MEDAS-2G-04', 16.00, NOW(), 'excel_authoritative_import'),
  ('MUHA-MEDAS-2G-05', 16.00, NOW(), 'excel_authoritative_import'),
  ('MUHA-MEDAS-2G-06', 16.00, NOW(), 'excel_authoritative_import'),
  ('MUHA-MEDAS-2G-07', 16.00, NOW(), 'excel_authoritative_import'),
  ('MUHA-MEDAS-2G-08', 16.00, NOW(), 'excel_authoritative_import'),
  ('MUHA-MEDAS-2G-09', 16.00, NOW(), 'excel_authoritative_import'),
  ('MUHA-MEDAS-2G-10', 16.00, NOW(), 'excel_authoritative_import'),
  ('BOUTIQ-2G-01', 18.00, NOW(), 'excel_authoritative_import'),
  ('BOUTIQ-2G-02', 18.00, NOW(), 'excel_authoritative_import'),
  ('BOUTIQ-2G-03', 18.00, NOW(), 'excel_authoritative_import'),
  ('BOUTIQ-2G-04', 18.00, NOW(), 'excel_authoritative_import'),
  ('BOUTIQ-2G-05', 18.00, NOW(), 'excel_authoritative_import'),
  ('BOUTIQ-2G-06', 18.00, NOW(), 'excel_authoritative_import'),
  ('BOUTIQ-2G-07', 18.00, NOW(), 'excel_authoritative_import'),
  ('BOUTIQ-2G-08', 18.00, NOW(), 'excel_authoritative_import'),
  ('MUHA-MED-2G-01', 18.00, NOW(), 'excel_authoritative_import'),
  ('MUHA-MED-2G-02', 18.00, NOW(), 'excel_authoritative_import'),
  ('MUHA-MED-2G-03', 18.00, NOW(), 'excel_authoritative_import'),
  ('MUHA-MED-2G-04', 18.00, NOW(), 'excel_authoritative_import'),
  ('MUHA-MED-2G-05', 18.00, NOW(), 'excel_authoritative_import'),
  ('MUHA-MED-2G-06', 18.00, NOW(), 'excel_authoritative_import'),
  ('MUHA-MED-2G-07', 18.00, NOW(), 'excel_authoritative_import'),
  ('MUHA-MED-2G-08', 18.00, NOW(), 'excel_authoritative_import'),
  ('MUHA-MED-2G-09', 18.00, NOW(), 'excel_authoritative_import'),
  ('MUHA-MED-2G-10', 18.00, NOW(), 'excel_authoritative_import'),
  ('BOUTIQ-2G-3FLAV-01', 18.00, NOW(), 'excel_authoritative_import'),
  ('BOUTIQ-2G-3FLAV-02', 18.00, NOW(), 'excel_authoritative_import'),
  ('BOUTIQ-2G-3FLAV-03', 18.00, NOW(), 'excel_authoritative_import'),
  ('BOUTIQ-2G-3FLAV-04', 18.00, NOW(), 'excel_authoritative_import'),
  ('BOUTIQ-2G-3FLAV-05', 18.00, NOW(), 'excel_authoritative_import'),
  ('BOUTIQ-2G-3FLAV-06', 18.00, NOW(), 'excel_authoritative_import'),
  ('BOUTIQ-2G-3FLAV-07', 18.00, NOW(), 'excel_authoritative_import'),
  ('BOUTIQ-2G-3FLAV-08', 18.00, NOW(), 'excel_authoritative_import'),
  ('BOUTIQ-2G-3FLAV-09', 18.00, NOW(), 'excel_authoritative_import'),
  ('BOUTIQ-2G-3FLAV-10', 18.00, NOW(), 'excel_authoritative_import'),
  ('MUNCHIES-1G-01', 4.00, NOW(), 'excel_authoritative_import'),
  ('MUNCHIES-1G-02', 4.00, NOW(), 'excel_authoritative_import'),
  ('MUNCHIES-1G-03', 4.00, NOW(), 'excel_authoritative_import'),
  ('MUNCHIES-1G-04', 4.00, NOW(), 'excel_authoritative_import'),
  ('MUNCHIES-1G-05', 4.00, NOW(), 'excel_authoritative_import'),
  ('MUNCHIES-1G-06', 4.00, NOW(), 'excel_authoritative_import'),
  ('MUNCHIES-1G-07', 4.00, NOW(), 'excel_authoritative_import'),
  ('MUNCHIES-1G-08', 4.00, NOW(), 'excel_authoritative_import'),
  ('MUHA-MEDA-2G-INF-01', 21.00, NOW(), 'excel_authoritative_import'),
  ('MUHA-MEDA-2G-INF-02', 21.00, NOW(), 'excel_authoritative_import'),
  ('MUHA-MEDA-2G-INF-03', 21.00, NOW(), 'excel_authoritative_import'),
  ('MUNCHIES-2G-DONUT-01', 18.00, NOW(), 'excel_authoritative_import'),
  ('MUNCHIES-2G-DONUT-02', 18.00, NOW(), 'excel_authoritative_import'),
  ('MUNCHIES-2G-DONUT-03', 18.00, NOW(), 'excel_authoritative_import'),
  ('PACKWOODS-01', 18.00, NOW(), 'excel_authoritative_import'),
  ('PACKWOODS-02', 54.00, NOW(), 'excel_authoritative_import'),
  ('KAWS-CONES-01', 20.00, NOW(), 'excel_authoritative_import'),
  ('KAWS-CONES-02', 20.00, NOW(), 'excel_authoritative_import'),
  ('KAWS-CONES-03', 20.00, NOW(), 'excel_authoritative_import'),
  ('TO-THE-MOON-01', 20.00, NOW(), 'excel_authoritative_import'),
  ('TO-THE-MOON-02', 20.00, NOW(), 'excel_authoritative_import'),
  ('TO-THE-MOON-03', 20.00, NOW(), 'excel_authoritative_import'),
  ('FIDELS-01', 21.00, NOW(), 'excel_authoritative_import'),
  ('FIDELS-02', 21.00, NOW(), 'excel_authoritative_import'),
  ('FIDELS-03', 21.00, NOW(), 'excel_authoritative_import'),
  ('FIDELS-04', 21.00, NOW(), 'excel_authoritative_import'),
  ('FIDELS-05', 21.00, NOW(), 'excel_authoritative_import'),
  ('BUBBLE-HASH-01', 6.00, NOW(), 'excel_authoritative_import'),
  ('BUBBLE-HASH-02', 84.00, NOW(), 'excel_authoritative_import'),
  ('KAWS-MOONROCKS-02', 16.00, NOW(), 'excel_authoritative_import'),
  ('LOUD-SAUCE-01', 14.00, NOW(), 'excel_authoritative_import'),
  ('LOUD-SAUCE-02', 14.00, NOW(), 'excel_authoritative_import'),
  ('LOUD-SAUCE-03', 14.00, NOW(), 'excel_authoritative_import'),
  ('LOUD-SAUCE-04', 14.00, NOW(), 'excel_authoritative_import'),
  ('JUICED-EXTRACT-01', 11.00, NOW(), 'excel_authoritative_import'),
  ('JUICED-EXTRACT-02', 11.00, NOW(), 'excel_authoritative_import'),
  ('WHOLE-PLANT-STATIC-01', 12.00, NOW(), 'excel_authoritative_import'),
  ('WHOLE-PLANT-STATIC-02', 168.00, NOW(), 'excel_authoritative_import'),
  ('BESOS-LIVE-RESIN-01', 80.00, NOW(), 'excel_authoritative_import'),
  ('BESOS-LIVE-RESIN-02', 80.00, NOW(), 'excel_authoritative_import'),
  ('BESOS-LIVE-RESIN-03', 80.00, NOW(), 'excel_authoritative_import'),
  ('BESOS-LIVE-RESIN-04', 80.00, NOW(), 'excel_authoritative_import'),
  ('BESOS-LIVE-RESIN-05', 80.00, NOW(), 'excel_authoritative_import'),
  ('BESOS-LIVE-RESIN-06', 80.00, NOW(), 'excel_authoritative_import'),
  ('BESOS-LIVE-RESIN-07', 80.00, NOW(), 'excel_authoritative_import'),
  ('BESOS-LIVE-RESIN-08', 80.00, NOW(), 'excel_authoritative_import'),
  ('BESOS-LIVE-RESIN-09', 80.00, NOW(), 'excel_authoritative_import'),
  ('BESOS-LIVE-RESIN-10', 80.00, NOW(), 'excel_authoritative_import'),
  ('BESOS-LIVE-RESIN-11', 80.00, NOW(), 'excel_authoritative_import'),
  ('BESOS-LIVE-RESIN-12', 80.00, NOW(), 'excel_authoritative_import'),
  ('BESOS-LIVE-RESIN-13', 80.00, NOW(), 'excel_authoritative_import'),
  ('BESOS-LIVE-RESIN-14', 80.00, NOW(), 'excel_authoritative_import'),
  ('BESOS-LIVE-RESIN-15', 80.00, NOW(), 'excel_authoritative_import'),
  ('BESOS-LIVE-RESIN-16', 80.00, NOW(), 'excel_authoritative_import'),
  ('MUNCHIES-GUMMIES-01', 4.00, NOW(), 'excel_authoritative_import'),
  ('MUNCHIES-GUMMIES-02', 4.00, NOW(), 'excel_authoritative_import'),
  ('MUNCHIES-GUMMIES-03', 4.00, NOW(), 'excel_authoritative_import'),
  ('PUNCH-BAR-01', 11.00, NOW(), 'excel_authoritative_import'),
  ('PUNCH-BAR-02', 11.00, NOW(), 'excel_authoritative_import'),
  ('PUNCH-BAR-03', 11.00, NOW(), 'excel_authoritative_import'),
  ('PUNCH-BAR-04', 11.00, NOW(), 'excel_authoritative_import'),
  ('PUNCH-BAR-05', 11.00, NOW(), 'excel_authoritative_import'),
  ('PUNCH-BAR-06', 11.00, NOW(), 'excel_authoritative_import'),
  ('PUNCH-BAR-07', 11.00, NOW(), 'excel_authoritative_import'),
  ('PUNCH-BAR-08', 11.00, NOW(), 'excel_authoritative_import'),
  ('PUNCH-BAR-09', 11.00, NOW(), 'excel_authoritative_import'),
  ('PUNCH-BAR-10', 11.00, NOW(), 'excel_authoritative_import'),
  ('PUFF-LA-GUMMIES-01', 9.00, NOW(), 'excel_authoritative_import'),
  ('PUFF-LA-GUMMIES-02', 9.00, NOW(), 'excel_authoritative_import'),
  ('PUFF-LA-GUMMIES-03', 9.00, NOW(), 'excel_authoritative_import'),
  ('PUFF-LA-GUMMIES-04', 9.00, NOW(), 'excel_authoritative_import'),
  ('PUFF-LA-GUMMIES-05', 9.00, NOW(), 'excel_authoritative_import'),
  ('PUFF-LA-GUMMIES-06', 9.00, NOW(), 'excel_authoritative_import'),
  ('PUFF-LA-GUMMIES-07', 9.00, NOW(), 'excel_authoritative_import'),
  ('PUFF-LA-GUMMIES-08', 9.00, NOW(), 'excel_authoritative_import'),
  ('PUFF-LA-GUMMIES-09', 9.00, NOW(), 'excel_authoritative_import'),
  ('MONSTER-COOKIES-01', 9.00, NOW(), 'excel_authoritative_import'),
  ('MONSTER-COOKIES-02', 9.00, NOW(), 'excel_authoritative_import'),
  ('MONSTER-COOKIES-03', 9.00, NOW(), 'excel_authoritative_import'),
  ('MONSTER-COOKIES-04', 9.00, NOW(), 'excel_authoritative_import'),
  ('MONSTER-COOKIES-05', 9.00, NOW(), 'excel_authoritative_import'),
  ('MONSTER-COOKIES-06', 9.00, NOW(), 'excel_authoritative_import'),
  ('MONSTER-COOKIES-07', 9.00, NOW(), 'excel_authoritative_import'),
  ('SOURZ-GUMMIES-01', 10.00, NOW(), 'excel_authoritative_import'),
  ('SOURZ-GUMMIES-02', 10.00, NOW(), 'excel_authoritative_import'),
  ('SOURZ-GUMMIES-03', 10.00, NOW(), 'excel_authoritative_import'),
  ('SOURZ-GUMMIES-04', 10.00, NOW(), 'excel_authoritative_import'),
  ('SOURZ-GUMMIES-05', 10.00, NOW(), 'excel_authoritative_import'),
  ('CALI-GOLD-CHOC-01', 20.00, NOW(), 'excel_authoritative_import'),
  ('CALI-GOLD-CHOC-02', 20.00, NOW(), 'excel_authoritative_import'),
  ('CALI-GOLD-CHOC-03', 20.00, NOW(), 'excel_authoritative_import'),
  ('CALI-GOLD-CHOC-04', 20.00, NOW(), 'excel_authoritative_import'),
  ('CALI-GOLD-CHOC-05', 20.00, NOW(), 'excel_authoritative_import'),
  ('YMB-APPLE', 19.00, NOW(), 'excel_authoritative_import'),
  ('YMB-MANGO', 19.00, NOW(), 'excel_authoritative_import'),
  ('YMB-STRAW-APL', 19.00, NOW(), 'excel_authoritative_import'),
  ('YMB-STRAW-BAN', 19.00, NOW(), 'excel_authoritative_import'),
  ('FADED-GUMMIES-01', 7.00, NOW(), 'excel_authoritative_import'),
  ('FADED-GUMMIES-02', 7.00, NOW(), 'excel_authoritative_import'),
  ('FADED-GUMMIES-03', 7.00, NOW(), 'excel_authoritative_import'),
  ('FADED-GUMMIES-04', 7.00, NOW(), 'excel_authoritative_import'),
  ('FADED-GUMMIES-05', 7.00, NOW(), 'excel_authoritative_import'),
  ('FADED-GUMMIES-06', 7.00, NOW(), 'excel_authoritative_import'),
  ('FADED-GUMMIES-07', 7.00, NOW(), 'excel_authoritative_import'),
  ('FADED-GUMMIES-08', 7.00, NOW(), 'excel_authoritative_import'),
  ('FADED-GUMMIES-09', 7.00, NOW(), 'excel_authoritative_import'),
  ('FADED-GUMMIES-10', 7.00, NOW(), 'excel_authoritative_import'),
  ('FADED-GUMMIES-11', 7.00, NOW(), 'excel_authoritative_import'),
  ('FADED-GUMMIES-12', 7.00, NOW(), 'excel_authoritative_import'),
  ('FADED-GUMMIES-13', 7.00, NOW(), 'excel_authoritative_import'),
  ('SILLY-GUMMIES-01', 19.00, NOW(), 'excel_authoritative_import'),
  ('SILLY-GUMMIES-02', 19.00, NOW(), 'excel_authoritative_import'),
  ('SILLY-GUMMIES-03', 19.00, NOW(), 'excel_authoritative_import'),
  ('SILLY-GUMMIES-04', 19.00, NOW(), 'excel_authoritative_import'),
  ('SILLY-GUMMIES-05', 19.00, NOW(), 'excel_authoritative_import'),
  ('SILLY-GUMMIES-06', 19.00, NOW(), 'excel_authoritative_import'),
  ('SILLY-GUMMIES-07', 19.00, NOW(), 'excel_authoritative_import'),
  ('BLUEBERRY-GHOST-OG-01', 9.00, NOW(), 'excel_authoritative_import'),
  ('BLUEBERRY-GHOST-OG-02', 65.00, NOW(), 'excel_authoritative_import'),
  ('GELATO-CAKE-01', 9.00, NOW(), 'excel_authoritative_import'),
  ('GELATO-CAKE-02', 65.00, NOW(), 'excel_authoritative_import'),
  ('PEANUT-BUTTER-SOUFFLE-01', 10.00, NOW(), 'excel_authoritative_import'),
  ('PEANUT-BUTTER-SOUFFLE-02', 19.00, NOW(), 'excel_authoritative_import'),
  ('PEANUT-BUTTER-SOUFFLE-03', 38.00, NOW(), 'excel_authoritative_import'),
  ('PEANUT-BUTTER-SOUFFLE-04', 75.00, NOW(), 'excel_authoritative_import'),
  ('CANDY-BACIO-01', 10.00, NOW(), 'excel_authoritative_import'),
  ('CANDY-BACIO-02', 19.00, NOW(), 'excel_authoritative_import'),
  ('CANDY-BACIO-03', 38.00, NOW(), 'excel_authoritative_import'),
  ('CANDY-BACIO-04', 75.00, NOW(), 'excel_authoritative_import'),
  ('SUPER-RUNTZ-01', 10.00, NOW(), 'excel_authoritative_import'),
  ('SUPER-RUNTZ-02', 19.00, NOW(), 'excel_authoritative_import'),
  ('SUPER-RUNTZ-03', 38.00, NOW(), 'excel_authoritative_import'),
  ('SUPER-RUNTZ-04', 75.00, NOW(), 'excel_authoritative_import'),
  ('KIND-CANNA-MINI-10PK-01', 20.00, NOW(), 'excel_authoritative_import'),
  ('KIND-CANNA-MINI-10PK-02', 20.00, NOW(), 'excel_authoritative_import'),
  ('KIND-CANNA-MINI-10PK-03', 20.00, NOW(), 'excel_authoritative_import'),
  ('NUGZ-MEDICATED-CHOCOLATES-01', 10.00, NOW(), 'excel_authoritative_import'),
  ('NUGZ-MEDICATED-CHOCOLATES-02', 10.00, NOW(), 'excel_authoritative_import'),
  ('NUGZ-MEDICATED-CHOCOLATES-03', 10.00, NOW(), 'excel_authoritative_import'),
  ('NUGZ-MEDICATED-CHOCOLATES-04', 10.00, NOW(), 'excel_authoritative_import'),
  ('NUGZ-MEDICATED-CHOCOLATES-05', 10.00, NOW(), 'excel_authoritative_import'),
  ('KOKO-DABZ-01', 16.00, NOW(), 'excel_authoritative_import'),
  ('KOKO-DABZ-02', 16.00, NOW(), 'excel_authoritative_import'),
  ('KOKO-DABZ-03', 16.00, NOW(), 'excel_authoritative_import'),
  ('KOKO-DABZ-04', 16.00, NOW(), 'excel_authoritative_import'),
  ('KOKO-DABZ-05', 16.00, NOW(), 'excel_authoritative_import'),
  ('HEIGHTS-01', 16.00, NOW(), 'excel_authoritative_import'),
  ('HEIGHTS-02', 16.00, NOW(), 'excel_authoritative_import'),
  ('TANGERINE-COOKIES-01', 9.00, NOW(), 'excel_authoritative_import'),
  ('TANGERINE-COOKIES-02', 17.00, NOW(), 'excel_authoritative_import'),
  ('TANGERINE-COOKIES-03', 33.00, NOW(), 'excel_authoritative_import'),
  ('TANGERINE-COOKIES-04', 65.00, NOW(), 'excel_authoritative_import'),
  ('BLUE-RIVER-LIVE-HASH-ROSIN-01', 15.00, NOW(), 'excel_authoritative_import'),
  ('BLUE-RIVER-LIVE-HASH-ROSIN-02', 15.00, NOW(), 'excel_authoritative_import'),
  ('BLUE-RIVER-ROSIN-CAPSULE-01', 10.00, NOW(), 'excel_authoritative_import'),
  ('BLUE-RIVER-ROSIN-CAPSULE-02', 10.00, NOW(), 'excel_authoritative_import'),
  ('KAWS-THC-INFUSED-SYRUP-01', 12.00, NOW(), 'excel_authoritative_import'),
  ('KAWS-THC-INFUSED-SYRUP-02', 12.00, NOW(), 'excel_authoritative_import'),
  ('KAWS-THC-INFUSED-SYRUP-03', 12.00, NOW(), 'excel_authoritative_import'),
  ('KAWS-THC-INFUSED-SYRUP-04', 12.00, NOW(), 'excel_authoritative_import'),
  ('KAWS-THC-INFUSED-SYRUP-05', 12.00, NOW(), 'excel_authoritative_import'),
  ('GELATO-01', 7.00, NOW(), 'excel_authoritative_import'),
  ('GELATO-02', 13.00, NOW(), 'excel_authoritative_import'),
  ('GELATO-03', 25.00, NOW(), 'excel_authoritative_import'),
  ('GELATO-04', 50.00, NOW(), 'excel_authoritative_import'),
  ('LEMON-CHERRY-GELATO-01', 10.00, NOW(), 'excel_authoritative_import'),
  ('LEMON-CHERRY-GELATO-02', 19.00, NOW(), 'excel_authoritative_import'),
  ('LEMON-CHERRY-GELATO-03', 38.00, NOW(), 'excel_authoritative_import'),
  ('LEMON-CHERRY-GELATO-04', 75.00, NOW(), 'excel_authoritative_import'),
  ('CANNALOPE-HAZE-01', 7.00, NOW(), 'excel_authoritative_import'),
  ('CANNALOPE-HAZE-02', 13.00, NOW(), 'excel_authoritative_import'),
  ('CANNALOPE-HAZE-03', 25.00, NOW(), 'excel_authoritative_import'),
  ('CANNALOPE-HAZE-04', 50.00, NOW(), 'excel_authoritative_import'),
  ('GG4-01', 9.00, NOW(), 'excel_authoritative_import'),
  ('GG4-02', 17.00, NOW(), 'excel_authoritative_import'),
  ('GG4-03', 33.00, NOW(), 'excel_authoritative_import'),
  ('GG4-04', 65.00, NOW(), 'excel_authoritative_import'),
  ('LEMON-VENOM-01', 10.00, NOW(), 'excel_authoritative_import'),
  ('LEMON-VENOM-02', 19.00, NOW(), 'excel_authoritative_import'),
  ('LEMON-VENOM-03', 38.00, NOW(), 'excel_authoritative_import'),
  ('LEMON-VENOM-04', 75.00, NOW(), 'excel_authoritative_import');

-- =====================================================
-- VERIFICATION QUERIES
-- =====================================================

-- Count imported costs
SELECT COUNT(*) as total_costs FROM public.sku_costs;

-- Check cost coverage against inventory
SELECT
  (SELECT COUNT(*) FROM wix_inventory_live) as total_inventory_skus,
  (SELECT COUNT(*) FROM sku_costs) as total_cost_skus,
  (SELECT COUNT(*) FROM wix_inventory_live i INNER JOIN sku_costs c ON c.sku = i.sku) as matched_skus,
  ROUND(
    (SELECT COUNT(*) FROM wix_inventory_live i INNER JOIN sku_costs c ON c.sku = i.sku)::numeric /
    NULLIF((SELECT COUNT(*) FROM wix_inventory_live), 0) * 100, 2
  ) as cost_coverage_percent;

-- SKUs in inventory without cost (UNMAPPED)
SELECT i.sku, i.product_name, 'UNMAPPED_SKU' as status
FROM wix_inventory_live i
LEFT JOIN sku_costs c ON c.sku = i.sku
WHERE c.sku IS NULL
ORDER BY i.sku;

-- SKUs in cost table not in inventory (orphaned)
SELECT c.sku, 'COST_NO_INVENTORY' as status
FROM sku_costs c
LEFT JOIN wix_inventory_live i ON i.sku = c.sku
WHERE i.sku IS NULL
ORDER BY c.sku;